# Generated by Django 6.0.1 on 2026-01-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_developerprofile_past_projects_portfolioproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100)),
                ('suggested_team', models.JSONField()),
                ('team_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('skills_coverage', models.JSONField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-team_score'],
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
