# Generated by Django 5.1.5 on 2026-01-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapplication',
            name='ai_reasoning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='experience_fit_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='match_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='matching_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='missing_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='portfolio_quality_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='skill_match_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
